### ISSUE TITLE
Using the author.cover accessor instead of hardcoding sidebar_bg.jpg in the sass file?

### ISSUE THREAD

**Issue by elsherbini** [damianmuti/sticko#1]
This is meant to be labelled as a "question" issue.

Forgive me if I am missing something obvious.

I am unable to use my uploaded cover image from the ghost admin panel as the cover image for my blog. I see in the _sidebar.scss file it says:

```
#main-sidebar {
...
    @include background-size(cover !important);
    background-image: url(../images/sidebar_bg.jpg);
...}
```

I don't see how to override this in one of the .hbs files to use the author.cover accessor. I suspect this has something to do with the line below in the script.js file?

```
    mainImage = $('img[alt="cover-image"]');
    if ( mainImage.length > 0){
          mainImageSource = mainImage.attr('src');
          $('#main-sidebar').css('background', 'url('+mainImageSource+')');
          mainImage.remove();
    }
```

**Comment by damianmuti** [comment]
This theme does not take any advantages of the author.cover feature since it uses blog.cover instead.
That small jQuery snippet you quoted is related to set the post cover feature since it's not included in Ghost's core.
