### ISSUE TITLE
Disqus: Profile Pictures do not appear.

### ISSUE THREAD

**Issue by LeCoupa** [damianmuti/sticko#16]
I don't really know what is happening here but the profile pictures do not appear inside the disqus box. (see [journal.gentlenode.com](http://journal.gentlenode.com/meteor-6-reactive-and-nonreactive-join-with-mongodb/))

I have contacted the support and they told me:

_Basically, Disqus waits to load avatars until the browser viewport gets close to the Disqus embed, loading them just in time. If your site is scrolling a whole < div > for the page, Disqus will never see that the viewport is on the Disqus embed._

I have noticed that the images appear on the mobile due to the responsive design. I'm trying different hacks but I did not find one that works at the moment. If someone have an idea on how we can fix this problem?

**Comment by thesabbir** [comment]
@LeCoupa I am having exactly same issue.

**Comment by LeCoupa** [comment]
I never managed to solve this issue, I'm not using this theme anymore. :(
